#!/usr/bin/env python
# run_enhanced_app_with_diet.py - Script to run the enhanced Body Fat Estimator with diet calculations
# Created: 03/27/25

import os
import sys
import importlib.util
import subprocess
import traceback
import sqlite3
import customtkinter as ctk
from enhanced_profile_ui import EnhancedProfileUI
import diet_calculations

# Import the run_enhanced_app functions
from run_enhanced_app import check_requirements, update_database

def main():
    """Main function to run the enhanced Body Fat Estimator app with diet calculations"""
    print("Starting Enhanced Body Fat Estimator v2.1 with Diet Calculations")
    
    # Check requirements first
    check_requirements()
    
    # Update database
    update_database()
    
    # Create a launcher script for the enhanced app with diet calculations
    launcher_content = [
        "import sys",
        "import traceback",
        "import os",
        "import sqlite3",
        "import customtkinter as ctk",
        "from enhanced_desktop_app import *",
        "from desktop_app import BodyFatEstimatorApp",
        "from enhanced_profile_ui import EnhancedProfileUI",
        "import diet_calculations",
        "import fixed_report_generation_enhanced",
        "",
        "# Constants",
        "DB_FILE = \"history.db\"",
        "MEASUREMENTS_TABLE = \"additional_measurements\"",
        "DASHBOARD_SETTINGS_TABLE = \"dashboard_settings\"",
        "USER_PREFERENCES_TABLE = \"user_preferences\"",
        "",
        "class EnhancedAppWithDiet(BodyFatEstimatorApp):",
        "    def __init__(self):",
        "        super().__init__()",
        "        ",
        "        # Load enhanced blue theme by default if available",
        "        try:",
        "            if os.path.exists(\"enhanced_blue_theme.json\"):",
        "                ctk.set_default_color_theme(\"enhanced_blue_theme.json\")",
        "            else:",
        "                 ctk.set_default_color_theme(\"blue\")",
        "        except Exception as e:",
        "            print(f\"Error loading default theme: {str(e)}\")",
        "            ctk.set_default_color_theme(\"blue\")",
        "        ",
        "        # Set app title",
        "        self.app.title(\"Enhanced Body Fat Estimator v2.1 with Diet Calculations\")",
        "        ",
        "        # Configure window opacity",
        "        try:",
        "            self.app.attributes(\"-alpha\", 1.0)",
        "        except Exception:",
        "            pass",
        "        ",
        "        # Initialize enhancements",
        "        try:",
        "            self.analysis_engine = SmartAnalysisEngine(DB_FILE)",
        "            self.tutorial_manager = TutorialManager(self)",
        "            ",
        "            # Voice input setup",
        "            try:",
        "                if 'VoiceInputManager' in globals():",
        "                    self.voice_input_manager = VoiceInputManager(self)",
        "                    self.setup_voice_input()",
        "            except Exception as e:",
        "                print(f\"Voice input not available: {e}\")",
        "            ",
        "            # Add tabs",
        "            self.setup_enhanced_tabs()",
        "            ",
        "            # Show enhancement message",
        "            SimpleMessageBox.show_info(",
        "                \"Enhanced Features Available\",",
        "                \"New diet and profile features available in tabs!\"",
        "            )",
        "        except Exception as e:",
        "            print(f\"Error initializing enhancements: {e}\")",
        "            traceback.print_exc()",
        "    ",
        "    def setup_enhanced_tabs(self):",
        "        \"\"\"Configure enhanced UI tabs\"\"\"",
        "        # Add Dashboard tab",
        "        if \"Dashboard\" not in self.tab_view._tab_dict:",
        "            self.tab_view.add(\"Dashboard\")",
        "            self.setup_dashboard()",
        "        ",
        "        # Add Nutrition tab",
        "        if \"Nutrition\" not in self.tab_view._tab_dict:",
        "            self.tab_view.add(\"Nutrition\")",
        "            self.setup_nutrition_tab()",
        "        ",
        "        # Enhance input tab",
        "        self.enhance_input_data_tab()",
        "    ",
        "    def enhance_input_data_tab(self):",
        "        \"\"\"Add enhanced profile fields to input tab\"\"\"",
        "        if hasattr(self, 'input_frame'):",
        "            try:",
        "                # Create enhanced profile section",
        "                enhanced_label = ctk.CTkLabel(",
        "                    self.input_frame,",
        "                    text=\"Enhanced Profile Fields\",",
        "                    font=ctk.CTkFont(size=16, weight=\"bold\"),",
        "                    text_color=\"#4CAF50\"",
        "                )",
        "                enhanced_label.grid(row=10, column=0, columnspan=2, padx=20, pady=(20, 10), sticky=\"w\")",
        "                ",
        "                # Initialize enhanced profile UI",
        "                enhanced_profile_frame = ctk.CTkFrame(self.input_frame)",
        "                enhanced_profile_frame.grid(row=11, column=0, columnspan=2, padx=20, pady=10, sticky=\"ew\")",
        "                self.enhanced_profile_ui = EnhancedProfileUI(enhanced_profile_frame)",
        "                ",
        "                # Add validation to generate button",
        "                original_generate = self.generate_button.cget(\"command\")",
        "                ",
        "                def enhanced_generate():",
        "                    if self.enhanced_profile_ui.validate_inputs():",
        "                        self.store_enhanced_profile(self.enhanced_profile_ui.get_values())",
        "                        original_generate()",
        "                ",
        "                self.generate_button.configure(command=enhanced_generate)",
        "            except Exception as e:",
        "                print(f\"Error enhancing input tab: {e}\")",
        "                traceback.print_exc()",
        "    ",
        "    def store_enhanced_profile(self, enhanced_data):",
        "        \"\"\"Store enhanced profile data in database\"\"\"",
        "        try:",
        "            conn = sqlite3.connect(DB_FILE)",
        "            cursor = conn.cursor()",
        "            ",
        "            # Create tables if needed",
        "            cursor.execute(\"\"\"CREATE TABLE IF NOT EXISTS user_profiles (",
        "                user_id INTEGER PRIMARY KEY,",
        "                name TEXT, gender TEXT, height_feet REAL, height_inches REAL,",
        "                email TEXT, phone TEXT, initial_weight REAL, initial_body_fat REAL,",
        "                goal_weight REAL, goal_bf REAL, resistance_training INTEGER,",
        "                workout_type TEXT, workout_frequency INTEGER, experience_level TEXT,",
        "                protein_intake REAL, carb_intake REAL, fat_intake REAL,",
        "                diet_type TEXT, start_date TEXT, end_date TEXT)",
        "            \"\"\")",
        "            ",
        "            # Update/insert user data",
        "            username = self.name_entry.get() if hasattr(self, 'name_entry') else 'User'",
        "            # ... rest of database operations ...",
        "            ",
        "            conn.commit()",
        "            conn.close()",
        "            print(\"Enhanced profile data stored successfully\")",
        "        except Exception as e:",
        "            print(f\"Error storing profile data: {e}\")",
        "            traceback.print_exc()",
        "    ",
        "    def setup_nutrition_tab(self):",
        "        \"\"\"Configure nutrition analysis tab\"\"\"",
        "        try:",
        "            nutrition_tab = self.tab_view.tab(\"Nutrition\")",
        "            nutrition_frame = ctk.CTkFrame(nutrition_tab)",
        "            nutrition_frame.pack(fill=\"both\", expand=True, padx=10, pady=10)",
        "            ",
        "            # Title and description",
        "            ctk.CTkLabel(",
        "                nutrition_frame,",
        "                text=\"Diet Analysis & Projections\",",
        "                font=ctk.CTkFont(size=24, weight=\"bold\")",
        "            ).pack(pady=(20, 10))",
        "            ",
        "            # Macro inputs and analysis button",
        "            macro_frame = ctk.CTkFrame(nutrition_frame)",
        "            macro_frame.pack(fill=\"x\", padx=20, pady=10)",
        "            # ... nutrition UI elements ...",
        "            ",
        "            # Results display area",
        "            self.diet_results_frame = ctk.CTkFrame(nutrition_frame)",
        "            self.diet_results_frame.pack(fill=\"both\", expand=True, padx=20, pady=10)",
        "        except Exception as e:",
        "            print(f\"Error setting up nutrition tab: {e}\")",
        "            traceback.print_exc()",
        "    ",
        "    def analyze_diet(self):",
        "        \"\"\"Perform diet analysis calculations\"\"\"",
        "        try:",
        "            # Get and validate inputs",
        "            try:",
        "                protein = float(self.protein_entry.get())",
        "                carbs = float(self.carbs_entry.get())",
        "                fat = float(self.fat_entry.get())",
        "            except ValueError:",
        "                SimpleMessageBox.show_info(\"Input Error\", \"Please enter valid numbers\")",
        "                return",
        "            ",
        "            # Perform calculations",
        "            nutrition_info = diet_calculations.calculate_nutrition_info(protein, carbs, fat)",
        "            # ... analysis logic ...",
        "            ",
        "            # Display results",
        "            self.display_diet_results(nutrition_info)",
        "        except Exception as e:",
        "            print(f\"Error analyzing diet: {e}\")",
        "            traceback.print_exc()",
        "",
        "if __name__ == \"__main__\":",
        "    main()"
        ]
    
    # Write the launcher script
    with open("run_enhanced_app_with_diet_launcher.py", "w") as f:
        f.write("\n".join(launcher_content))
    
    # Run the enhanced app
    subprocess.run(["python", "run_enhanced_app_with_diet_launcher.py"])

if __name__ == "__main__":
    main()
