import { useState, useEffect } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { useToast } from "@/components/ui/use-toast";
import { Bot, RefreshCw } from "lucide-react";
import { getReportCommentary } from "@/lib/aiService";
import { ReportData } from "@/lib/reportingService";

interface AiReportCommentaryProps {
  reportData: ReportData;
}

export function AiReportCommentary({ reportData }: AiReportCommentaryProps) {
  const { toast } = useToast();
  const [commentary, setCommentary] = useState<string>("");
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    if (reportData) {
      fetchCommentary();
    }
  }, [reportData]);

  const fetchCommentary = async () => {
    setIsLoading(true);
    try {
      const response = await getReportCommentary(reportData);
      setCommentary(response);
    } catch (error) {
      console.error("Error fetching AI commentary:", error);
      toast({
        title: "Error",
        description: "Failed to load AI commentary. Please try again later.",
        variant: "destructive",
      });
    } finally {
      setIsLoading(false);
    }
  };

  const refreshCommentary = () => {
    fetchCommentary();
    toast({
      title: "Refreshing Commentary",
      description: "Generating new AI analysis of your progress...",
    });
  };

  // Format the commentary text with paragraphs
  const formattedCommentary = commentary
    .trim()
    .split("\n\n")
    .filter(paragraph => paragraph.trim().length > 0);

  return (
    <Card>
      <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
        <div>
          <CardTitle className="text-xl flex items-center">
            <Bot className="h-5 w-5 mr-2 text-primary" />
            AI Analysis
          </CardTitle>
          <CardDescription>
            Personalized commentary on your progress
          </CardDescription>
        </div>
        <Button 
          variant="outline" 
          size="sm" 
          onClick={refreshCommentary}
          disabled={isLoading}
        >
          {isLoading ? (
            <span className="flex items-center">
              <span className="animate-spin h-4 w-4 mr-2 border-b-2 border-primary rounded-full"></span>
              Loading
            </span>
          ) : (
            <span className="flex items-center">
              <RefreshCw className="h-4 w-4 mr-2" />
              Refresh
            </span>
          )}
        </Button>
      </CardHeader>
      <CardContent>
        {isLoading ? (
          <div className="flex items-center justify-center py-8">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
          </div>
        ) : commentary ? (
          <div className="space-y-4 text-muted-foreground">
            {formattedCommentary.map((paragraph, index) => (
              <p key={index}>{paragraph}</p>
            ))}
            <div className="text-xs text-muted-foreground mt-4 pt-2 border-t">
              <em>Generated by AI based on your progress data. This is not medical advice.</em>
            </div>
          </div>
        ) : (
          <div className="text-center py-8 text-muted-foreground">
            <p>No AI commentary available. Click refresh to generate analysis.</p>
          </div>
        )}
      </CardContent>
    </Card>
  );
}